version: "3.0"
services: 
  nginx:
    image: nginx
    restart: always
    ports:
      - 9082:80
      - 9083:8080
      - 9084:8081
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/conf.d/:/etc/nginx/conf.d/
      - ./nginx_logs/:/var/log/nginx/
      - ./dist/:/usr/app/
  web:
    build: .
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    restart: always
    environment:
      - TZ=Asia/Shanghai
volumes:
  node_modules: