version: "3.0"
services: 
  web:
    build: .
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - "8082:3000"    
    restart: always
    environment:
      - TZ=Asia/Shanghai
volumes:
  node_modules: