version: "3.0"
services: 
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 9082:80
      - 9083:8080
      - 9084:8081
    volumes:
      - ./logrotate_config/nginx:/etc/logrotate.d/nginx
      - ./logrotate_config/crontab:/etc/cron.d/logrotate-cron
      - ./logrotate_config/crontab.sh:/usr/script/crontab.sh
      - ./logrotate_config/cron.log:/var/log/cron.log
      #- ./logrotate_config/logrotate.conf:/etc/logrotate.conf
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/conf.d/:/etc/nginx/conf.d/
      - ./nginx_logs/:/var/log/nginx/
      - ./dist/:/usr/app/
  web:
    build: .
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    restart: always
    environment:
      - TZ=Asia/Shanghai
volumes:
  node_modules: